apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: s3-object-store-echo-postgresql
  namespace: cnpg-system
spec:
  configuration:
    destinationPath: "s3://wal-archival/"
    endpointURL: "http://minio:9000/"
    s3Credentials:
      accessKeyId:
        name: minio-wal-archival-creds
        key: ACCESS_KEY_ID
      secretAccessKey:
        name: minio-wal-archival-creds
        key: ACCESS_SECRET_KEY
    wal:
      compression: gzip
  retentionPolicy: "30d"