apiVersion: postgresql.cnpg.io/v1
kind: Subscription
metadata:
  name: cnpg-postgresql-publisher
  namespace: cnpg-system
spec:
  cluster:
    name: cnpg-postgresql-publisher
  dbname: app
  name: subscriber
  externalClusterName: legacy-postgresql-publisher
  publicationName: all_tables_pub