apiVersion: postgresql.cnpg.io/v1
kind: Subscription
metadata:
  name: echo-postgresql-migrated-subscription
  namespace: cnpg-system
spec:
  cluster:
    name: echo-postgresql-migrated
  dbname: echo
  name: subscriber
  externalClusterName: postgresql-publisher
  publicationName: all_tables_pub