---
apiVersion: v1
kind: Secret
metadata:
  name: echo-postgresql-16-9-logical-replication-creds
  namespace: cnpg-system
  labels:
    cnpg.io/reload: "true"
data:
  username: bG9naWNhbF9yZXBsaWNhdGlvbg==
  password: bG9naWNhbF9yZXBsaWNhdGlvbg==
type: kubernetes.io/basic-auth
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: echo-postgresql-16-9
  namespace: cnpg-system
spec:
  imageName: ghcr.io/cloudnative-pg/postgresql:16.9
  instances: 2
  storage:
    size: 1Gi
    storageClass: gtf-ack-essd-pl0-wait
  managed:
    roles:
      - name: logical_replication
        login: true
        replication: true
        ensure: present
        passwordSecret:
          name: echo-postgresql-16-9-logical-replication-creds
        inRoles:
          - app
  walStorage:
    size: 1Gi
    storageClass: gtf-ack-essd-pl0-wait
  primaryUpdateStrategy: unsupervised
  primaryUpdateMethod: switchover
  postgresql:
    parameters:
      archive_timeout: "10min"
    synchronous:
      method: any
      number: 1
      dataDurability: required
  backup:
    target: prefer-standby
    volumeSnapshot:
      className: alibabacloud-disk-snapshot
      online: false
  plugins:
  - name: barman-cloud.cloudnative-pg.io
    isWALArchiver: true
    parameters:
      barmanObjectName: s3-object-store-wal-archival
  resources:
    requests:
      cpu: 100m
      memory: 512Mi
    limits:
      cpu: 500m
      memory: 1Gi
        
    