
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: echo-postgresql-18-0
  namespace: cnpg-system
spec:
  imageName: ghcr.io/cloudnative-pg/postgresql:18.0
  instances: 2
  externalClusters:
  - name: echo-postgresql-16-9
    connectionParameters:
      host: echo-postgresql-16-9-rw.cnpg-system.svc.cluster.local
      user: logical_replication
      dbname: app
    password:
      name: echo-postgresql-16-9-logical-replication-creds
      key: password
  bootstrap:
    initdb:
      import:
        type: microservice
        schemaOnly: true
        databases:
          - app
        source:
          externalCluster: echo-postgresql-16-9
  storage:
    size: 1Gi
    storageClass: gtf-ack-essd-pl0-wait
  walStorage:
    size: 1Gi
    storageClass: gtf-ack-essd-pl0-wait
  primaryUpdateStrategy: unsupervised
  primaryUpdateMethod: switchover
  postgresql:
    parameters:
      archive_timeout: "10min"
    synchronous:
      method: any
      number: 1
      dataDurability: required
  backup:
    target: prefer-standby
    volumeSnapshot:
      className: alibabacloud-disk-snapshot
      online: false
  plugins:
  - name: barman-cloud.cloudnative-pg.io
    isWALArchiver: true
    parameters:
      barmanObjectName: s3-object-store-wal-archival
  resources:
    requests:
      cpu: 100m
      memory: 512Mi
    limits:
      cpu: 500m
      memory: 1Gi
        
    